name: cirta
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48698
title: 'Cirta Securité & Services'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f1a17'
    - '#da251c'
    - '#ffffff'
    - '#dad8d7'
    - '#92918f'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.48803857644088566
  rhythmicContrast: 0.32337654288858175
purpose: []
